### ISSUE TITLE
Sequential model input variable file

### ISSUE THREAD

**Issue by JCZeng1** [lwtnn/lwtnn#129]
Right now a template for the variable file is provided for the sequential model.
I understand that the Functional model is recommended. However, is there any technical challenge to generate the input variable file (with keras2json.py) for the sequential model?

**Comment by dguest** [comment]
the input variable file is very similar to the one for the graph model, the only difference that there's one less level of nesting. The basic format is given [in this wiki page](https://github.com/lwtnn/lwtnn/wiki/Keras-Converter#sequential-model-input-variable-file), does that help?

Just to confirm, though, I _strongly_ recommend using the functional model API in keras. Also, even if you are going to use the sequential API in Keras, I'd recommend converting your lwtnn model to the functional one so you can use the `LightweightGraph` class within C++ code. There's a script called `sequential2functional.py` in this repository to do that conversion.

**Comment by JCZeng1** [comment]
The basic format in the wiki page is helpful, but it is always concerning when a user needs to do this manually.
On the other hand, I didn't realize one can do the conversion between the two models. I will try your recommendation and see how it goes.

**Comment by dguest** [comment]
You don't have to make the file manually: it's JSON is so you can write code that spits out the file. The example is there so people can understand the format, but of course I strongly encourage everyone to write code to produce these files. It's very error prone to enter this information manually.

**Comment by JCZeng1** [comment]
Yes, I agree that a script is needed to properly generate the file.

> There's a script called converters/sequential2graph.py in this repository to do that conversion.

I don't think this script is working as intended. I tried it with Keras 2.3.1 & 2.4.0. The python script is expecting a different format than what Keras Sequential API created.

**Comment by matthewfeickert** [comment]
> I don't think this script is working as intended. I tried it with Keras 2.3.1 & 2.4.0. The python script is expecting a different format than what Keras Sequential API created.

@JCZeng1 can you post the commands that you're currently running (such that with the files they should be copy & pasteable) and then the output / the problems that you're experiencing? That would probably be helpful in understanding the core of the problem.

**Comment by JCZeng1** [comment]
@dguest , @matthewfeickert , I misunderstood when the sequential2graph.py should be used; after seeing Dan's latest comment, I realized the python script should be used after keras2json.py. I tried it with the sequential model and got the converted functional model.

**Comment by matthewfeickert** [comment]
> I tried it with the sequential model and got the converted functional model.

@JCZeng1 cool. Are things fully working now then (and this Issue can get closed)? Or are there still additional issues?
