### ISSUE TITLE
Linting with pre-commit hooks?

### ISSUE THREAD

**Issue by matthewfeickert** [lwtnn/lwtnn#132]
@dguest What are your feelings about running linting with `pre-commit` hooks (both in CI and optionally with pre-commit installed locally)? I'm not suggesting trying to enforce a C++ style linter or anything like that (as much as I'd like that :wink:) but more about just using a subset of https://github.com/pre-commit/pre-commit-hooks.

If you like the idea I have a branch on my fork that is ready to go for a PR that I can demo with you as well. (c.f. https://github.com/matthewfeickert/lwtnn/runs/2522324028)

**Comment by dguest** [comment]
I'm fine with some linting, although I'm not sure what specific rules we need: It's good to check that the json, python and C++ aren't wrong. That said, in the case of the C++ it might be simpler to tell CMake to be more strict compiling. Is there any way to enable this stuff only on lines that actually change in a merge request? I took a look at your branch and I admit I didn't understand why some things had to be changed.

**Comment by matthewfeickert** [comment]
> Is there any way to enable this stuff only on lines that actually change in a merge request?

Yup, by default that's what happens on a PR.

> I took a look at your branch and I admit I didn't understand why some things had to be changed.

I ran `pre-commit run --all-files` to have a uniform starting place. Some of the files in `lwtnn` had DOS line endings, so I ran a `dos2unix` over them to make diffs easier in the future, but we can discuss this stuff and what to drop in a PR.

**Comment by jwsmithers** [comment]
Run pre-commit hooks!! They help everyone :)

**Comment by matthewfeickert** [comment]
> Run pre-commit hooks!! They help everyone

Hard agree @jwsmithers. :) The only reason I said "optional" earlier is that I can imagine some developers coming from ATLAS might not be down with the idea of learning how to use them, but having them in CI at least catches things.
