### ISSUE TITLE
Test build against gcc11

### ISSUE THREAD

**Issue by dguest** [lwtnn/lwtnn#136]
Some ATLAS friends [reported problems building in GCC 11](https://its.cern.ch/jira/browse/ATLINFR-4147). The error is something about us using `size_t` outside the `std::` namespace.

More generally, it might be good to have a few images around with custom compilers installed, to catch issues like this. @matthewfeickert might be able to take a look. If it's easy to add this to CI that would be awesome.

**Comment by matthewfeickert** [comment]
```
```

**Comment by dguest** [comment]
Nice find. We just need boost and Eigen3. They are both header only so install should be easy (I'm pretty sure property-tree doesn't need any of the stuff that boost::jam or whatever requires.
