### ISSUE TITLE
Zenodo sync not working

### ISSUE THREAD

**Issue by dguest** [lwtnn/lwtnn#179]
I just tagged release 2.14.1 and, for some reason, the sync with Zenodo isn't working

<img width="1238" alt="image" src="https://github.com/user-attachments/assets/1201139b-a333-4991-a7e2-31834b5b09e9">

@matthewfeickert have you seen this before? The last release we tagged was apparently about 2 years ago so I guess something about github permissions might have changed.

**Comment by matthewfeickert** [comment]
I can look at it tomorrow, but I think there might have been a desync last year. Can you check who owns the Zenodo archive (aka whose account it shows up under: yours or mine)? You can also email the Zenodo team to fix archives that did't sync.

**Comment by dguest** [comment]
Thanks, I own it, and I already filed some kind of help request with the team using [their support link](https://zenodo.org/support). 

It's not a big rush but I'm trying to update some citations for a paper and stumbled on this one. I thought you might have seen it before. It sounds like you have, thanks for pointing to the zenodo team.

**Comment by matthewfeickert** [comment]
Okay yeah. Go check that the repo is still selected to sync under the Zenodo GitHub settings. The team should be able to quickly get the missing release up.

**Comment by dguest** [comment]
Yeah I guess I should have said, I have this:
<img width="976" alt="image" src="https://github.com/user-attachments/assets/c6837343-0c02-4e8d-a70d-40d22c706bb4">
when I flick the switch:
<img width="962" alt="image" src="https://github.com/user-attachments/assets/74a9c241-ac47-483c-9abf-0ba56e8e8325">
error box disappears after a moment, reappears when I flick it back on, then disappears again.

**Comment by matthewfeickert** [comment]
@dguest okay keep it to "on" and let's see what the Zenodo team says. You can just use the general project DOI and keep moving with getting the citation in the paper you want.

**Comment by dguest** [comment]
They had to do a manual sync, seems to be working now.

**Comment by matthewfeickert** [comment]
Great. Yeah, https://doi.org/10.5281/zenodo.14276439 is up now.
