### ISSUE TITLE
building lwtnn with custom boost

### ISSUE THREAD

**Issue by smuzaffar** [lwtnn/lwtnn#35]
In order to use our boost installation we had to patch makefile 
https://github.com/smuzaffar/cmsdist/blob/cc07391e4f1b8f6a4b00ce17fbc604ada7b539a0/lwtnn-1.0-boost-fix.patch

would it be possible to provide a way so that custom boost and flags can be set instead of patching the makefile?

**Comment by dguest** [comment]
Would this solve your problem: https://github.com/lwtnn/lwtnn/commit/7d5a8fcc47a985eba68b5abe935a0f43b58dc3af
?

**Comment by smuzaffar** [comment]
thanks, this should be enough.

**Comment by dguest** [comment]
OK, merged into master
