### ISSUE TITLE
Add unit test for LSTM

### ISSUE THREAD

**Issue by dguest** [lwtnn/lwtnn#37]
There's currently no unit test for the LSTM layer, which is a bit uncomfortable given that we're now using an LSTM in ATLAS flavor tagging.

**Comment by jwsmithers** [comment]
There also is no GRU layer unit test. Will add them both.

**Comment by dguest** [comment]
Actually this tests it: 

https://github.com/lwtnn/lwtnn/blob/master/tests/test-ipmp.sh

but maybe it should be renamed or something to make what it's testing more clear.

**Comment by jwsmithers** [comment]
aha, it does indeed. Well, I probably should have looked at that file anyways to make sure, and it's pretty obvious then.

**Comment by dguest** [comment]
I guess in the future we should name tests to reflect what they actually do. A file called `test-ipmp.sh` doesn't really accomplish that, so it's my mistake. Something like `test-keras-lwtnn-gru-maxout-highway.sh` would probably be more clear.

**Comment by jwsmithers** [comment]
Ok, I can change the names. Similarly, for DL1 test then.

**Comment by jwsmithers** [comment]
This can probably be closed by the way. 
See the new naming conventions here: https://github.com/lwtnn/lwtnn/tree/master/tests

**Comment by dguest** [comment]
We have coverage for GRUs, but do we have LSTMs? I don't see which test covers these.

**Comment by jwsmithers** [comment]
Good point... don't close yet. :)

**Comment by dguest** [comment]
Can we close this now?

**Comment by jwsmithers** [comment]
Yup!
