### ISSUE TITLE
Add regression test for Keras merge layers

### ISSUE THREAD

**Issue by dguest** [lwtnn/lwtnn#47]
There's an example model here: https://github.com/dguest/lwtnn-tutorial-for-btaggers/blob/master/make-keras-model.py

**Comment by jwsmithers** [comment]
this and porting merge layers to keras 2

**Comment by dguest** [comment]
Merge layers work: I tested them. The ["merge" layer that you may be worrying about][1] is just a hack to support embedding in the sequential API, and we should probably remove it anyway. Sorry if that was confusing.

[1]: https://github.com/lwtnn/lwtnn/blob/52bd5c82d8e1e201510988cf976aa36fa3f48dbb/converters/keras_v2_layer_converters.py#L94-L135

**Comment by dguest** [comment]
I wrote [a tutorial][1] which sort-of-works that goes through creating a functional model with a merge layer using Keras 2. While doing that I verified that the concatenate layer does indeed work and do what I'd expect. I'm not sure if we have a test case for Keras v1 though.

I was thinking about writing a regression test around the toy network that I define there, but we have to solve #45 first since that model has multiple output nodes and we don't currently handle those well in the regression tests.

[1]: https://github.com/dguest/lwtnn-tutorial-for-btaggers

**Comment by jwsmithers** [comment]
ya ok I'm confused now. So merge layers that work are for the functional API when merging two nodes (or something like that) within the reconstruction of the NN itself? I.e. nothing to do with the converter?

**Comment by jwsmithers** [comment]
Crossed messages...
That's quite a tutorial 😮 
I'll have a read through

**Comment by dguest** [comment]
This is done for the functional api now, so I'm closing #45 and closing this.
