### ISSUE TITLE
New tag for CMake version?

### ISSUE THREAD

**Issue by jwsmithers** [lwtnn/lwtnn#58]
What version do you want to put in AtlasExternals? It probably shouldn't be master. But are we ready for a new tag?

**Comment by dguest** [comment]
I just created one. I don't see why we're not ready, but let me know if you have any problems.

**Comment by jwsmithers** [comment]
Thanks, wasn't sure how things were going with the time regression layer.

**Comment by dguest** [comment]
The time distributed dense layer should be working (at least it does with my setup using Keras 2.0), so I think we should be good to go.
