### ISSUE TITLE
Maintain tensorflow and theano parameter saving between versions

### ISSUE THREAD

**Issue by jwsmithers** [lwtnn/lwtnn#72]
From an email with Andreas Sogaard he reported an error when trying to convert a NN.

```
>>> File "/afs/cern.ch/work/a/asogaard/private/lwtnn/converters/keras_v2_layer_converters.py", line 52, in _normalization_parameters
>>>     gamma = layers['gamma'+BACKEND_SUFFIX]
>>> KeyError: 'gamma:0'

which appears to be related to the converters reading of the HDF5 weights file. The `layer_group` and `layers` in question are

>>> layer_group = <HDF5 group "/classifier/batch_normalization_1" (1 members)>
>>> layers = {'batch_normalization_1_1': array(['beta:0', 'gamma:0', 'moving_mean:0', 'moving_variance:0'], dtype='<U17’)}

I have attached the outputs from json.tool and h5ls for the architecture- and weights files, resp. They look pretty healthy to me, e.g. 

$ cat output_h5ls.txt | head -9
/                        Group
/classifier              Group
/classifier/batch_normalization_1 Group
/classifier/batch_normalization_1/classifier Group
/classifier/batch_normalization_1/classifier/batch_normalization_1_1 Group
/classifier/batch_normalization_1/classifier/batch_normalization_1_1/beta:0 Dataset {10}
/classifier/batch_normalization_1/classifier/batch_normalization_1_1/gamma:0 Dataset {10}
/classifier/batch_normalization_1/classifier/batch_normalization_1_1/moving_mean:0 Dataset {10}
/classifier/batch_normalization_1/classifier/batch_normalization_1_1/moving_variance:0 Dataset {10}

for 10 input variables, but what do I know. I am saving the model in a setup with the following package versions:
  Python version: 2.7.13 (so not python3)
  Numpy version: 1.13.1
  Keras version: 2.0.8
  TensorFlow version: 1.3.0
```

However, it actually looks like the gamma:0 does exist. This will need to be looked into. He also sent architecture and weights file which I won't attach here.

**Comment by dguest** [comment]
I wonder which group it's looking for `gamma:0` in though. 

I don't remember exactly which versions of Keras and tensorflow we tested this with before: did we use Keras 2 with the tensorflow backend yet?

**Comment by jwsmithers** [comment]
For the Keras 2 update this was for tensorflow and theano. I thought we had a unit test for tensorflow, but I don't remember playing with the travis CI to do this.
Regardless, I tested it locally and at least it initially worked.  I'll dig up what versions later.

**Comment by dguest** [comment]
This makes me wonder if we should rethink the testing a bit: right now the approach is to save a network with some version of Keras, and then to download the network to run the converter and lwtnn. This is good to check that the later part of the chain works, in that it assures the same network always gives us the same values.

On the other hand, it doesn't make it especially easy to test against multiple Keras versions and backends. Maybe it's worth adding a few scripts that build example Keras models and convert them to json. This way we could just add a new Tensorflow / Keras combination to the build matrix to make sure everything works.

**Comment by jwsmithers** [comment]
I would agree with this. The question is how limited are we with Travis? It would also be good to add different OS's, but they probably don't support very many.

**Comment by dguest** [comment]
They support a few versions of Ubuntu and supposedly OSX, but the support is more limited for things with mixed-language dependencies (we need C++ and Keras in the same package). But setting up a build matrix by changing environment variables isn't super difficult, you just need to include something like:

```
env:
 - KERAS_BACKEND=theano KERAS_VERSION=2.0.3 BUILD=make
 - KERAS_BACKEND=tensorflow KERAS_VERSION=2.0.3 BUILD=make
...
before_install:
 - pip install keras=$KERAS_VERSION
...
```

Then you can add other combinations of environment variables. Maybe there's a cleaner way to deal with all the combinations of (build system * keras version * backend) but actually I don't think we need to test every possible combination since I assume the build system should factor out.

**Comment by dguest** [comment]
Hey so can we close this @jwsmithers?

**Comment by jwsmithers** [comment]
Yup!
