### ISSUE TITLE
Using lwtnn from python code

### ISSUE THREAD

**Issue by rdisipio** [lwtnn/lwtnn#85]
Hi guys,

  I would like to use lwtnn from a python program. I trained a model using Keras, but for deployment I would like to "replace" in my python program the old cut-based event selection with the DNN. Is there an easy way to load lwtnn from python? Perhaps via PyROOT (which will be necessary anyway)? 

Cheers,
Riccardo

**Comment by dguest** [comment]
Hi,

If you're running your program in python why can't you use Keras directly? This code was really designed specifically for cases where using Keras directly would be difficult (i.e. in C++ code).

But if you do want to use lwtnn from python, you have a lot of options in terms of ways to wrap C++ code: you could use pyroot, or you could use swig, or boost.python, or a number of other wrappers.

**Comment by rdisipio** [comment]
Hi,

  my problem is to obtain a coherent configuration with Keras, TF-GPU, PyROOT on a non-lxplus CentOS machine. I was just wondering if there was any off-the-shelf solution. 

r.

**Comment by dguest** [comment]
I assume you didn't have any luck with `pip install keras`? If you're already depending on a lot of ROOT stuff then the best bet is probably to build this library into your C++ code.

I'll think about a stand-alone python object that supports lwtnn, maybe that would be nice. If I were to do it I would probably write it in C using the c-python api, but in any case I don't think it would be part of the lwtnn repo, maybe another repo that uses lwtnn as a submodule.

**Comment by dguest** [comment]
Hi @rdisipio, I'm wondering if you've had any luck here. These days we're recommending docker images for a lot of these types of things, which you [can often run via singularity][1]. This will be standard software for the LHC so I expect your admins will support it soon if they don't already.

As for pyroot, are you sure you need it? Can you use [uproot][2] instead?

[1]: https://gitlab.cern.ch/aml/containers/docker/tree/feature/add-singularity-use-instructions#running-on-lxplus-with-singularity
[2]: https://github.com/scikit-hep/uproot
