### ISSUE TITLE
How does our swish function compare to keras-contrib version

### ISSUE THREAD

**Issue by dguest** [lwtnn/lwtnn#87]
@aghoshpub added a swish function here, but apparently [it exists in keras-contrib][1]. There's probably no good reason to maintain it in both places.

[1]: https://github.com/keras-team/keras-contrib/blob/master/keras_contrib/layers/advanced_activations/swish.py

**Comment by aghoshpub** [comment]
Looks like it's doing the same thing as mine.

 I had to add ```self.__name__ = 'swish'``` to get it to save the architecture on my Keras, I'm not sure how this one can get away without doing that. Perhaps a newer version of Keras doesn't require it anymore.

**Comment by dguest** [comment]
OK, well my fault for not knowing about keras-contrib when we added this. 

We should try out their version at some point, I'm sure they'd be more than happy to accept a merge request if the layer that's given there doesn't save.

**Comment by aghoshpub** [comment]
I tried loading a pretrained model with this architecture (with minimal changes to match the names, initialisation structure of my Swish) and it seems to work. Even without ```self.__name__ = 'swish'``` . So I think we can get rid of ours and just use the keras contrib version. I believe from lwtnn side the two will look identical, but it has to be tested. I'll do it when I find some time.

When I was making my swish function I didn't find this keras-contrib implementation, if it was already there, perhaps it was hidden away in some file with a not so obvious name. Google searches pointed only to SO back then.

**Comment by dguest** [comment]
OK, well if you can confirm please make a PR to remove it. Also, should you feel so inclined, you sholud add yourself and your ORCID to [this list][1].

[1]: https://github.com/lwtnn/lwtnn/blob/master/.zenodo.json#L3-L33

**Comment by aghoshpub** [comment]
So the two architectures are definitely do not look identical to lwtnn. I've been trying to find the differences we have to address. I'm not sure yet how much we need to change lwtnn to accommodate this.

**Comment by dguest** [comment]
Do you think the changes could be accommodated on the converter side?

**Comment by aghoshpub** [comment]
Yes I think so. The differences are only in the way the weights are saved, name of variable and the info being saved in the architecture file. All of it can be dealt with on the converter side.

**Comment by aghoshpub** [comment]
One major problem with the contrib version is that if the beta is not trainable, it is not saved in the weight .h5 file. So lwtnn cannot pick it up from there. It's saved instead in the architecture .json file.

**Comment by dguest** [comment]
I think we should be doing two things here:
  - We should make a MR to keras-contrib which includes the trainable swish implementation (just to preempt someone else doing so and then having to support that as well)
 - We should add support for whatever keras-contrib provides.

I'm not sure if they'll want to change the implementation of something that already exists, but we might as well give it a shot.

**Comment by aghoshpub** [comment]
I already made an issue and a tentative MR:
 https://github.com/keras-team/keras-contrib/issues/482

If the keras-contrib implementation stays as it is, we will have to pick up the `beta` parameter from the architecture .json file instead of the weights .h5 file. But I would feel more future safe if we could pick it up from the weights file.

**Comment by aghoshpub** [comment]
I've implemented the changes to the converter in my local copy of lwtnn. It should work with the keras-contrib swish and it is quite easy to save my old keras models (trained with my swish) in a way that it looks the same as the new swish to lwtnn converters. So we don't need to support two versions.

On second thoughts I think there's no real need to make a MR to keras-contrib, as long as any new version of a trainable swish also saves the `beta` in the config.
